module.exports = {
    "extends": "airbnb",
    "rules": {
        "max-len": ["warn", {"code": 150}],
        "indent": ["error", 4, {"SwitchCase": 1,  "ignoredNodes": ["JSXAttribute", "JSXSpreadAttribute"]}],
        "comma-dangle": ["error", "never"],
        "object-curly-spacing": ["error", "never"],
        "object-shorthand": ["error", "never"],
        "object-curly-newline": "off",
        "no-unused-vars": ["warn", {"args": "none"}],
        "no-mixed-operators": "off",
        "no-param-reassign": "off",
        "no-inner-declarations": "off",
        "no-restricted-globals": "off",
        "no-empty": ["error", {"allowEmptyCatch": true}],
        "no-new": "warn",
        "no-restricted-syntax": "off",
        "no-underscore-dangle": "off",
        "no-prototype-builtins": "off",
        "no-shadow": "off",
        "no-nested-ternary": "off",
        "no-plusplus": "off",
        "no-use-before-define": "off",
        "import/prefer-default-export": "off",
        "radix": "off",
        "class-methods-use-this": "off",
        "func-names": "off",
        "arrow-parens": "off",
        "prefer-arrow-callback": "off",
        "prefer-destructuring": "off",
        "prefer-template": "off",
        "dot-notation": "off",
        "function-paren-newline": "off",
        "operator-assignment": "off",
        "react/jsx-no-bind": "warn",
        "react/jsx-indent": ["error", 4],
        "react/jsx-boolean-value": "off",
        "react/jsx-filename-extension": "off",
        "react/jsx-closing-bracket-location": "off",
        "react/jsx-tag-spacing": ["error", {"beforeSelfClosing": "allow"}],
        "react/jsx-indent-props": "off",
        "react/jsx-first-prop-new-line": "off",
        "react/no-danger": "off",
        "react/no-string-refs": "warn",
        "react/prefer-stateless-function": "off",
        "react/forbid-prop-types": "off",
        "react/self-closing-comp": "off",
        "react/no-array-index-key": "off",
        "react/sort-comp": "off",
        "react/no-unused-state": "off",
        "jsx-a11y/media-has-caption": "off",
        "jsx-a11y/anchor-is-valid": "off",
        "jsx-a11y/alt-text": "off",
        "jsx-a11y/no-static-element-interactions": "off",
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/no-noninteractive-element-interactions": "off",
        "jsx-a11y/label-has-for": "off",
        "jsx-quotes": ["error", "prefer-double"]
    },
    "parser": "babel-eslint"
};
